services:
  - type: web
    name: shortlisting-ai
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    branch: main
    rootDir: backend
    envVars:
      - fromGroup: shortlisting-env