/**
 * frontend/src/api/axios.js
 *
 * ✅ FIX (CRITICAL) — Removed hardcoded Content-Type header
 * ──────────────────────────────────────────────────────────────
 * BUG: Setting `Content-Type: multipart/form-data` on the axios
 * instance (or per-request) WITHOUT a boundary parameter causes
 * the FastAPI backend to fail parsing the multipart body entirely.
 *
 * The `boundary` string (e.g. "----WebKitFormBoundaryXYZ") is
 * auto-generated by the browser and appended by axios when it
 * detects a FormData object. Manually overriding Content-Type
 * discards the boundary → server sees a malformed body → upload
 * always fails with a 422 or silent 200 + "Upload failed."
 *
 * FIX: Do NOT set Content-Type at all on the axios instance.
 * For JSON requests axios sets it automatically.
 * For FormData requests axios sets multipart + boundary automatically.
 * Never override it manually.
 *
 * ✅ FIX 2 — Export BACKEND constant for use in cleanup fetch()
 * calls (e.g. navigator.sendBeacon / fetch with keepalive: true)
 * where the axios instance is not available.
 */

import axios from 'axios'

export const BACKEND = import.meta.env.VITE_API_URL || 'http://localhost:8000'

const api = axios.create({
  baseURL: BACKEND,
  // ✅ DO NOT set Content-Type here — axios handles it automatically:
  //    - JSON body    → Content-Type: application/json
  //    - FormData     → Content-Type: multipart/form-data; boundary=----xyz
  // Hardcoding 'multipart/form-data' without the boundary breaks uploads.
  withCredentials: false,
})

// ── Request interceptor: attach JWT token ────────────────────────────────────
api.interceptors.request.use(
  (config) => {
    const token =
      localStorage.getItem('token') ||
      sessionStorage.getItem('token')

    if (token) {
      config.headers.Authorization = `Bearer ${token}`
    }

    // ✅ CRITICAL: Never set Content-Type for FormData requests.
    // Axios detects FormData and sets the correct multipart header + boundary.
    // Removing any manual Content-Type override that might have been here.
    if (config.data instanceof FormData) {
      delete config.headers['Content-Type']
    }

    return config
  },
  (error) => Promise.reject(error)
)

// ── Response interceptor: handle auth errors globally ────────────────────────
api.interceptors.response.use(
  (response) => response,
  (error) => {
    if (error.response?.status === 401) {
      // Token expired or invalid — clear storage and redirect to login
      localStorage.removeItem('token')
      sessionStorage.removeItem('token')
      if (window.location.pathname !== '/login') {
        window.location.href = '/login'
      }
    }
    return Promise.reject(error)
  }
)

export default api